apiVersion: apps/v1
kind: Deployment
metadata:
  name: nxiq-deployment
  labels:
    app: nxiq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nxiq
  template:
    metadata:
      labels:
        app: nxiq
    spec:
      containers:
      - name: nxiq
        image: sonatype/nexus-iq-server
        ports:
        - containerPort: 8070
        resources:
          limits:
            memory: 1Gi
        volumeMounts:
          - mountPath: /sonatype-work
            name: nxiq-pv-storage
          - mountPath: /etc/nexus-iq-server
            name: config-volume
      volumes:
        - name: nxiq-pv-storage
          persistentVolumeClaim:
            claimName: nxiq-pv-claim
        - name: config-volume
          configMap:
            name: nxiq-config
            items:
              - key: config.yml
                path: config.yml
