{{- if .Values.iq.imagePullSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "iqserver.name" . }}
data:
  .dockerconfigjson: {{ .Values.iq.imagePullSecret }}

type: kubernetes.io/dockerconfigjson
{{- end }}