{{- if .Values.ingress.enabled -}}
{{- $fullName := include "nexus-iq.fullname" . -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
spec:
  backend:
    serviceName: {{ $fullName }}
    servicePort: {{ .Values.ingress.adminPort }}
{{- end }}
