apiVersion: v1
kind: Service
metadata:
  name: nxiq-service
spec:
  selector:
    app: nxiq
  ports:
  - name: ui
    protocol: TCP
    port: 8070
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nxiq-config
data:
  config.yml: |
    server:
      applicationConnectors:
        - type: http
          port: 8070
      adminConnectors:
        - type: http
          port: 8071
    createSampleData: true
    sonatypeWork: /sonatype-work
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nxiq-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/nxiq/
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nxiq-pv-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nxiq-deployment
  labels:
    app: nxiq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nxiq
  template:
    metadata:
      labels:
        app: nxiq
    spec:
      containers:
      - name: nxiq
        image: sonatype/nexus-iq-server
        ports:
        - containerPort: 8070
        resources:
          limits:
            memory: 1Gi
        volumeMounts:
          - mountPath: /sonatype-work
            name: nxiq-pv-storage
          - mountPath: /etc/nexus-iq-server
            name: config-volume
      volumes:
        - name: nxiq-pv-storage
          persistentVolumeClaim:
            claimName: nxiq-pv-claim
        - name: config-volume
          configMap:
            name: nxiq-config
            items:
              - key: config.yml
                path: config.yml
