apiVersion: v1
kind: Service
metadata:
  name: nxiq-service
spec:
  selector:
    app: nxiq
  ports:
  - name: ui
    protocol: TCP
    port: 8070
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nxiq-config
data:
  config.yml: |
    server:
      applicationConnectors:
        - type: http
          port: 8070
      adminConnectors:
        - type: http
          port: 8071
    createSampleData: true
    sonatypeWork: /sonatype-work
