apiVersion: v1
name: sonatype-nexus
version: 0.1.0
appVersion: 3.20.1-01
description: Sonatype Nexus is an open source repository manager
keywords:
  - artifacts
  - dependency
  - management
  - sonatype
  - nexus
  - repository
home: https://www.sonatype.com/nexus-repository-oss
icon: https://www.sonatype.com/hubfs/2019%20Product%20logo/Vertical/NexusRepo_Vertical.svg
sources:
  - https://github.com/sonatype/nexus-public
maintainers:
  - name: adrianpowell
    email: apowell@sonatype.com
  - name: jflinchbaugh
    email: jflinchbaugh@sonatype.com
  - name: fernau
    email: cfernau@sonatype.com
