apiVersion: v1
name: sonatype-nexus
version: 0.2.0
appVersion: 3.20.1-01
description: Sonatype Nexus is an open source repository manager
keywords:
  - artifacts
  - dependency
  - management
  - sonatype
  - nexus
  - repository
  - quickstart
  - ci
  - repository-manager
  - nexus3
home: https://www.sonatype.com/nexus-repository-oss
icon: https://www.sonatype.com/hubfs/2019%20Horizontal%20Product%20logo/horizontal%20Repo%20/Repo/NexusRepo_horiz.svg
sources:
  - https://github.com/sonatype/nexus-public
maintainers:
  - name: adrianpowell
    email: apowell@sonatype.com
  - name: jflinchbaugh
    email: jflinchbaugh@sonatype.com
  - name: fernau
    email: cfernau@sonatype.com
